services:
  backend:
    image: somebackend
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      SERVER_HOST: order-db
      SERVER_PORT: ${SERVER_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SSLMODE: ${DB_SSLMODE}
    ports:
      - "3000:3000"

  order-db:
    image: postgres:17
    container_name: order-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: